MAJOR=1
MINOR=0
PATCH=1


build: 
	g++  header_xml.cpp ../snapshot.cpp -O2 -fopenmp  -I../ -o lmp2x3d_$(MAJOR).$(MINOR).$(PATCH).out
debug: 
	g++  header_xml.cpp ../snapshot.cpp -O2 -fopenmp  -g  -I../ -o lmp2x3d_$(MAJOR).$(MINOR).$(PATCH).out
